---
- name: Basic router setup using Ansible
  hosts: routers
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Set router hostname to R1
      ios_config:
        lines:
          - hostname R1

    - name: Configure GigabitEthernet0/0 interface
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - description Managed by Ansible
          - ip address 192.168.1.1 255.255.255.0
          - no shutdown
