---
- name: Configure Cisco Router
  hosts: routers
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Set hostname
      ios_config:
        lines:
          - hostname R1

    - name: Configure interface Gig0/0
      ios_config:
        lines:
          - interface GigabitEthernet0/0
          - description Configured by Ansible
          - ip address 192.168.1.1 255.255.255.0
          - no shutdown
