---
- name: Set up 'developers' group and user environment
  hosts: all
  become: yes
  tasks:

    - name: Ensure the 'developers' group exists
      group:
        name: developers
        state: present

    - name: Add user 'bender' with bash shell and preset password
      user:
        name: bender
        shell: /bin/bash
        password: "$6$OStSJfA6FA$ffSDaJBWfSpmnwlC6QWJwLG3PgZWQhPYUSezmRvSiUFpwSWy/57KuUuLg/4yGBpKx2TWYsPDz9Yq7nL2I2XT3/"

    - name: Add 'bender' to the 'developers' group
      user:
        name: bender
        groups: developers
        append: yes

    - name: Create the /opt/engineering directory for the team
      file:
        path: /opt/engineering
        state: directory
        mode: '0750'
        group: developers

    - name: Create a private file inside /opt/engineering
      file:
        path: /opt/engineering/private.txt
        state: touch
        mode: '0770'
        group: developers
