---
# Playbook: Network Interface Status Report
# Descrip: Collects interface status from Cisco devices and generates reports in CSV and Markdown formats

- name: Collect interface status and generate reports
  hosts: cisco_devices
  gather_facts: no

  vars:
    report_dir: "./reports/interfaces"

  tasks:

    - name: Generate current timestamp for report filenames
      ansible.builtin.set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y-%m-%d_%H-%M') }}"
      delegate_to: localhost
      run_once: true

    - name: Make sure the report directory exists
      ansible.builtin.file:
        path: "{{ report_dir }}"
        state: directory
        mode: '0755'
      delegate_to: localhost

    - name: Retrieve interface status from Cisco devices
      cisco.ios.ios_command:
        commands:
          - show ip interface brief
          - show interfaces description
      register: interface_data

    - name: Generate CSV report from template
      ansible.builtin.template:
        src: ../templates/interface_report.csv.j2
        dest: "{{ report_dir }}/{{ inventory_hostname }}_interfaces_{{ timestamp }}.csv"
      delegate_to: localhost

    - name: Generate Markdown report from template
      ansible.builtin.template:
        src: ../templates/interface_report.md.j2
        dest: "{{ report_dir }}/{{ inventory_hostname }}_interfaces_{{ timestamp }}.md"
      delegate_to: localhost
      vars:
        report_time: "{{ lookup('pipe', 'date') }}"

    - name: Display generated report file paths
      ansible.builtin.debug:
        msg:
          - "CSV Report: {{ report_dir }}/{{ inventory_hostname }}_interfaces_{{ timestamp }}.csv"
          - "Markdown Report: {{ report_dir }}/{{ inventory_hostname }}_interfaces_{{ timestamp }}.md"
